version: '3'

services:
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=airlines
      - MYSQL_USER=ruben
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - ./postgres_data/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    build: .
    command: >
      sh -c "./wait_for_it.sh db:3306 -t 60 -- 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy