# Generated by Django 4.2 on 2024-11-15 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
